# Generated by Django 2.2.1 on 2019-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deaddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='starttime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
