# Generated by Django 2.2.1 on 2019-06-04 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20190603_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='users',
        ),
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
